server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mz-db?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:com/slx/boot/mzproject/mapper/*.xml
  type-aliases-package: com.slx.boot.zmproject.bean
  configuration:
    map-underscore-to-camel-case: true


